# Generated by Django 2.2.10 on 2020-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('searchText', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=200)),
            ],
        ),
    ]
